# Generated by Django 2.1.4 on 2018-12-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamoorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('user_stream', models.IntegerField(choices=[(1, 'Netflix'), (2, 'HboGo'), (3, 'Amazon Prime')])),
                ('password', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.IntegerField(choices=[(1, 'Netflix'), (2, 'HboGo'), (3, 'Amazon Prime')])),
                ('user_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.StreamoorUser')),
            ],
        ),
    ]
