# Generated by Django 2.1.4 on 2018-12-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_streamooruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamooruser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='streamooruser',
            name='password',
        ),
    ]
