# Generated by Django 2.1.4 on 2018-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_auto_20181218_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamooruser',
            name='user_stream',
            field=models.IntegerField(choices=[(1, 'Netflix'), (2, 'HBO GO'), (3, 'Amazon Prime')]),
        ),
        migrations.AlterField(
            model_name='usersstream',
            name='stream_type',
            field=models.IntegerField(choices=[(1, 'Netflix'), (2, 'HBO GO'), (3, 'Amazon Prime')]),
        ),
    ]
