# Generated by Django 2.1.4 on 2018-12-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_auto_20181219_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pierwszy', to='baza.StreamoorUser')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugi', to='baza.StreamoorUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='usersstream',
            name='user_stream',
        ),
        migrations.DeleteModel(
            name='UsersStream',
        ),
    ]
